---
- name: Install Zabbix repository
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/epel.repo
    insertafter: "[epel]"
    line: "excludepkgs=zabbix*"

- name: Add necessary RPM repositories
  ansible.builtin.yum_repository:
      name: "{{ item }}"
      baseurl: "{{ zabbix_agent2_repo }}"
      state: present
  loop:
    - "zabbix-agent2"
    - "zabbix-agent2-plugin-*"

- name: Copy Zabbix Agent2 configuration
  ansible.builtin.template:
    src: templates/zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix-agent
    group: zabbix-agent
    mode: 0644


- name: Start & Enable Zabbix Agent2
  ansible.builtin.systemd:
    name: zabbix-agent2
    enabled: yes
    state: started

- name: Enable Zabbix Agent2 in firewall
  ansible.builtin.firewalld:
    service: zabbix-agent2
    permanent: yes
    state: enabled
    immediate: yes