---
- name: Install Zabbix Agent on Linux & Windows Servers
  hosts: zabbix_agents
  roles:
    - role: linux-host-config
      when: ansible_facts['os_family'] != 'Windows'
    - role: linux-zabbix-agent
      when: ansible_facts['os_family'] != 'Windows'
    - role: windows-host-config
      when: ansible_facts['os_family'] == 'Windows'
    - role: windows-zabbix-agent
      when: ansible_facts['os_family'] == 'Windows'
