---
# tasks file for windows-zabbix-agent
- name: Check connectivity to Zabbix Server
  ansible.windows.win_shell: ping -c 1 {{ zabbix_server }}
  args:
    executable: cmd
  register: ping_result

- name: Stop running of remaining tasks if Zabbix Server is not reachable
  ansible.builtin.fail:
    msg: "Zabbix Server is not reachable from this host!"
    when: ping_result.rc != 0

- name: Install Zabbix Agent2
  chocolatey.chocolatey.win_chocolatey:
    name: zabbix-agent2
    state: present
  tags: zabbix-agent2

- name: Configure Zabbix Agent2
  community.windows.win_template:
    src: zabbix_agent2.conf.j2
    dest: C:\Program Files\Zabbix Agent2\zabbix_agent2.conf
  tags: zabbix-agent2

- name: Enable Zabbix Firewall Rule
  community.windows.win_firewall_rule:
    name: Zabbix Agent2
    localport: 10050
    action: allow
    direction: in
    protocol: TCP
  tags: zabbix-agent2

- name: Start Zabbix Agent2
  ansible.windows.win_service:
    name: zabbix-agent2
    start_mode: auto
    state: started
  tags: zabbix-agent2
