---
# tasks file for windows-host-config
- name: Set hostname on Windows hosts
  ansible.windows.win_hostname:
    name: "{{ ansible_hostname }}"
  tags: hostname

- name: Set timezone on Windows hosts
  community.windows.win_timezone:
    timezone: "{{ timezone }}"
  tags: timezone
