---
- name: Add necessary repositories
  ansible.builtin.get_url:
    url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb"
    dest: /tmp/zabbix-agent2.deb
    mode: 0644

- name: Add Zabbix Agent2 repository via dpkg
  ansible.builtin.apt:
    deb: /tmp/zabbix-agent2.deb
    state: present

- name: Install Zabbix Agent2 packages
  ansible.builtin.apt:
    pkg:
      - zabbix-agent2
      - zabbix-agent2-plugin-*

- name: Copy Zabbix Agent configuration
  ansible.builtin.template:
    src: templates/zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix-agent
    group: zabbix-agent
    mode: 0644

- name: Start & Enable Zabbix Agent2
  ansible.builtin.service:
      name: zabbix-agent2
      state: started
      enabled: yes

- name: Enable Zabbix Agent2 in firewall
  ansible.builtin.firewalld:
      service: zabbix-agent2
      permanent: yes
      state: enabled
      immediate: yes